{"region":"Northern Africa","country":"Algeria","land":"Algeria","population":44177969} ,
{"region":"Northern Africa","country":"Egypt","land":"Egypt, Arab Rep.","population":109262178} ,
{"region":"Northern Africa","country":"Libya","land":"Libya","population":6735277} ,
{"region":"Northern Africa","country":"Morocco","land":"Morocco","population":37076584} ,
{"region":"Northern Africa","country":"Sudan","land":"Sudan","population":45657202} ,
{"region":"Northern Africa","country":"Tunisia","land":"Tunisia","population":12262946} ,
{"region":"Middle Africa","country":"Angola","land":"Angola","population":34503774} ,
{"region":"Middle Africa","country":"Cameroon","land":"Cameroon","population":27198628} ,
{"region":"Middle Africa","country":"Central African Republic","land":"Central African Republic","population":5457154} ,
{"region":"Middle Africa","country":"Chad","land":"Chad","population":17179740} ,
{"region":"Middle Africa","country":"Congo","land":"Congo, Rep.","population":5835806} ,
{"region":"Middle Africa","country":"Democratic Republic of the Congo","land":"Congo, Dem. Rep.","population":95894118} ,
{"region":"Middle Africa","country":"Gabon","land":"Gabon","population":2341179} ,
{"region":"Middle Africa","country":"Sao Tome and Principe","land":"Sao Tome and Principe","population":223107} ,
{"region":"Western Africa","country":"Benin","land":"Benin","population":12996895} ,
{"region":"Western Africa","country":"Burkina Faso","land":"Burkina Faso","population":22100683} ,
{"region":"Western Africa","country":"Cabo Verde","land":"Cabo Verde","population":587925} ,
{"region":"Western Africa","country":"Cote d'Ivoire","land":"Cote d'Ivoire","population":27478249} ,
{"region":"Western Africa","country":"Equatorial Guinea","land":"Equatorial Guinea","population":1634466} ,
{"region":"Western Africa","country":"Gambia","land":"Gambia, The","population":2639916} ,
{"region":"Western Africa","country":"Ghana","land":"Ghana","population":32833031} ,
{"region":"Western Africa","country":"Guinea","land":"Guinea","population":13531906} ,
{"region":"Western Africa","country":"Guinea-Bissau","land":"Guinea-Bissau","population":2060721} ,
{"region":"Western Africa","country":"Liberia","land":"Liberia","population":5193416} ,
{"region":"Western Africa","country":"Mali","land":"Mali","population":22593590} ,
{"region":"Western Africa","country":"Mauritania","land":"Mauritania","population":4614974} ,
{"region":"Western Africa","country":"Niger","land":"Niger","population":25252722} ,
{"region":"Western Africa","country":"Nigeria","land":"Nigeria","population":213401323} ,
{"region":"Western Africa","country":"Senegal","land":"Senegal","population":16876720} ,
{"region":"Western Africa","country":"Sierra Leone","land":"Sierra Leone","population":8420641} ,
{"region":"Western Africa","country":"Togo","land":"Togo","population":8644829} ,
{"region":"Southern Africa","country":"Botswana","land":"Botswana","population":2588423} ,
{"region":"Southern Africa","country":"Lesotho","land":"Lesotho","population":2281454} ,
{"region":"Southern Africa","country":"Namibia","land":"Namibia","population":2530151} ,
{"region":"Southern Africa","country":"South Africa","land":"South Africa","population":59392255} ,
{"region":"Southern Africa","country":"Eswatini","land":"Eswatini","population":1192271} ,
{"region":"Eastern Africa","country":"Burundi","land":"Burundi","population":12551213} ,
{"region":"Eastern Africa","country":"Comoros","land":"Comoros","population":821625} ,
{"region":"Eastern Africa","country":"Djibouti","land":"Djibouti","population":1105557} ,
{"region":"Eastern Africa","country":"Eritrea","land":"Eritrea","population":3620312} ,
{"region":"Eastern Africa","country":"Ethiopia","land":"Ethiopia","population":120283026} ,
{"region":"Eastern Africa","country":"Kenya","land":"Kenya","population":53005614} ,
{"region":"Eastern Africa","country":"Madagascar","land":"Madagascar","population":28915653} ,
{"region":"Eastern Africa","country":"Malawi","land":"Malawi","population":19889742} ,
{"region":"Eastern Africa","country":"Mauritius","land":"Mauritius","population":1266334} ,
{"region":"Eastern Africa","country":"Mozambique","land":"Mozambique","population":32077072} ,
{"region":"Eastern Africa","country":"Rwanda","land":"Rwanda","population":13461888} ,
{"region":"Eastern Africa","country":"Seychelles","land":"Seychelles","population":99258} ,
{"region":"Eastern Africa","country":"Somalia","land":"Somalia","population":17065581} ,
{"region":"Eastern Africa","country":"South Sudan","land":"South Sudan","population":10748272} ,
{"region":"Eastern Africa","country":"Uganda","land":"Uganda","population":45853778} ,
{"region":"Eastern Africa","country":"Tanzania","land":"Tanzania","population":63588334} ,
{"region":"Eastern Africa","country":"Zambia","land":"Zambia","population":19473125} ,
{"region":"Eastern Africa","country":"Zimbabwe","land":"Zimbabwe","population":15993524} ,
